name: Build and Push Image to GHCR

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from package.json
        id: version
        run: |
          VERSION=$(jq -r '.version' app/package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if git tag already exists
        id: tag_check
        run: |
          TAG="${{ steps.version.outputs.version }}"
          if git rev-parse "refs/tags/$TAG" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Tag $TAG already exists â€” exiting"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop if version already exists
        if: steps.tag_check.outputs.exists == 'true'
        run: exit 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (with cache)
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Containerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/a-zurcher/lighthouse-api:latest
            ghcr.io/a-zurcher/lighthouse-api:${{ steps.version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max