name: Build and Push Image to GHCR

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from package.json
        id: version
        run: |
          VERSION=$(jq -r '.version' app/package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if container image tag already exists
        id: image_check
        continue-on-error: true
        run: |
          TAG="${{ steps.version.outputs.version }}"
          IMAGE="ghcr.io/a-zurcher/lighthouse-api:$TAG"
          
          if docker manifest inspect "$IMAGE" >/dev/null 2>&1; then
            echo "tag_doesnt_exist=false" >> "$GITHUB_OUTPUT"
            echo "Image $IMAGE already exists — stopping workflow"
            exit 1
          else
            echo "tag_doesnt_exist=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Early exit
        if: steps.image_check.outputs.tag_doesnt_exist == 'false'
        run: echo "Skipping build — image tag already exists"

      - name: Set up Docker Buildx
        if: steps.image_check.outputs.tag_doesnt_exist == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (with cache)
        if: steps.image_check.outputs.tag_doesnt_exist == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Containerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/a-zurcher/lighthouse-api:latest
            ghcr.io/a-zurcher/lighthouse-api:${{ steps.version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max